/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "election.h"

void election_1(char *host) {
  CLIENT *clnt;
  char voter_name[32];
  char candidate_name[32];
  char voter_gender;
  char voter_id[10];

  char **new_voter_id;
  bool_t *success;
  candidate_list *c_list;
  char **winner;
  stats *result;

#ifndef DEBUG
  clnt = clnt_create(host, ELECTION, ELECTIONVERS, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
#endif /* DEBUG */

  int choice;
  int super_choice;

  do {
    printf("\n");
    printf("1. Register to Vote\n");
    printf("2. Verify Voter\n");
    printf("3. Vote\n");
    printf("4. Tally Results\n");
    printf("5. Announce Winner\n");
    printf("6. Supervisor Mode\n");
    printf("0. Quit\n\n");
    printf("Please Enter your Choice: ");

    scanf("%d", &choice);

    switch (choice) {
    case 1:
      printf("Enter voter name: ");
      scanf(" %[^\n]s", voter_name);
      printf("Enter voter gender: ");
      scanf(" %c", &voter_gender);

      new_voter_id =
          register_voter_1(voter_name, voter_gender, clnt);
      if (new_voter_id == (char **)NULL)
        clnt_perror(clnt, "call failed");
      else
        printf("Voter Registered!\nNew Voter Id = %s\n", *new_voter_id);
      break;

    case 2:
      printf("Enter voter id: ");
      scanf(" %s", voter_id);

      success = verify_voter_1(voter_id, clnt);
      if (success == (bool_t *)NULL)
        clnt_perror(clnt, "call failed");
      else if (*success == TRUE)
        printf("Voter exists\n");
      else
        printf("No voter exists\n");
      break;

    case 3:
      printf("Enter voter id: ");
      scanf(" %s", voter_id);

      printf("Enter candidate name: ");
      scanf(" %s", candidate_name);

      success = cast_vote_1(voter_id, candidate_name, clnt);
      if (success == (bool_t *)NULL)
        clnt_perror(clnt, "call failed");
      else if (*success == TRUE)
        printf("Vote was cast successfully\n");
      else
        printf("Vote cannot be cast\n");
      break;

    case 4:
      c_list = tally_results_1(clnt);
      if (c_list == (candidate_list *)NULL)
        clnt_perror(clnt, "call failed");
      else {
        for(int i = 0; i < c_list->candidate_list_len; i++)
          printf("\n%s: %d", c_list->candidate_list_val[i].name,
                 c_list->candidate_list_val[i].votes);
        printf("\n");
      }
      break;

    case 5:
      winner = announce_winner_1(clnt);
      if (winner == (char **)NULL)
        clnt_perror(clnt, "call failed");
      else
        printf("The winner is %s\n", *winner);
      break;

    case 6:
      do {
        printf("\n");
        printf("1. Add candidate\n");
        printf("2. Remove a candidate\n");
        printf("3. Invalidate a candidate\n");
        printf("4. Calculate statistics\n");
        printf("5. Quit and return to main menu\n\n");
        printf("Please Enter your Choice: ");

        scanf("%d", &super_choice);

        switch (super_choice) {
        case 1:
          printf("Enter candidate name: ");
          scanf("%s", candidate_name);

          success = add_candidate_1(candidate_name, clnt);
          if (success == (bool_t *)NULL)
            clnt_perror(clnt, "call failed");
          else if (*success == TRUE)
            printf("Candidate added successfully!\n");
          else
            printf("Candidate addition failed!\n");
          break;

        case 2:
          printf("Enter candidate name: ");
          scanf(" %s", candidate_name);

          success = remove_candidate_1(candidate_name, clnt);
          if (success == (bool_t *)NULL)
            clnt_perror(clnt, "call failed");
          else if (*success == TRUE)
            printf("Candidate removed successfully!\n");
          else
            printf("Candidate deletion failed!\n");
          break;

        case 3:
          printf("Enter candidate name: ");
          scanf(" %s", candidate_name);

          success = invalidate_candidate_1(candidate_name, clnt);
          if (success == (bool_t *)NULL)
            clnt_perror(clnt, "call failed");
          else if (*success == TRUE)
            printf("Candidate added successfully!\n");
          else
            printf("Candidate addition failed!\n");
          break;

        case 4:
          result = calc_statistics_1(clnt);
          if (result == (stats *)NULL)
            clnt_perror(clnt, "call failed");
          else {
            printf("%%age of registered that votes = %f\n",
                   result->total_vote_percent);
            printf("%%age of male voters = %f\n", result->male_vote_percent);
            printf("%%age of female that votes = %f\n",
                   result->female_vote_percent);
            printf("%%age of registered that votes = %f\n",
                   result->total_vote_percent);
          }
          break;

        case 5:
          break;

        default:
          printf("Invalid Choice\n");
        }
      } while (super_choice != 5);
      break;

    case 0:
      break;

    default:
      printf("Invalid Choice!\n");
    }
  } while (choice != 0);

#ifndef DEBUG
  clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[]) {
  char *host;

  if (argc < 2) {
    printf("usage: %s server_host\n", argv[0]);
    exit(1);
  }
  host = argv[1];
  election_1(host);
  exit(0);
}
