/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "election.h"

bool_t
xdr_voter (XDR *xdrs, voter *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->id, 9,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->gender))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->vote))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_candidate (XDR *xdrs, candidate *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->votes))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->valid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_candidate_stats (XDR *xdrs, candidate_stats *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->total_vote_percent))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->male_vote_percent))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->female_vote_percent))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_stats (XDR *xdrs, stats *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->total_vote_percent))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->male_vote_percent))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->female_vote_percent))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->candidate.candidate_val, (u_int *) &objp->candidate.candidate_len, ~0,
		sizeof (candidate_stats), (xdrproc_t) xdr_candidate_stats))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_voter_ptr (XDR *xdrs, voter_ptr *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (voter), (xdrproc_t) xdr_voter))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_candidate_list (XDR *xdrs, candidate_list *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->candidate_list_val, (u_int *) &objp->candidate_list_len, ~0,
		sizeof (candidate), (xdrproc_t) xdr_candidate))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_register_voter_1_argument (XDR *xdrs, register_voter_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->arg1, ~0))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cast_vote_1_argument (XDR *xdrs, cast_vote_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->arg1, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	return TRUE;
}
